// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPCc7FrTNnxrHmc-7oJUBH1dLA1IRavjw',
    appId: '1:324274357325:web:c7feb036276f5eae140804',
    messagingSenderId: '324274357325',
    projectId: 'prakmobile-9c0f6',
    authDomain: 'prakmobile-9c0f6.firebaseapp.com',
    storageBucket: 'prakmobile-9c0f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB82-5QQSnf3WTParuBpPV33StrXnQp4wU',
    appId: '1:324274357325:android:89e9871518b471fb140804',
    messagingSenderId: '324274357325',
    projectId: 'prakmobile-9c0f6',
    storageBucket: 'prakmobile-9c0f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-P7hvwMlMVWKkGdvRynzYTVk3HvPLfB0',
    appId: '1:324274357325:ios:86d9577a52d4fe3e140804',
    messagingSenderId: '324274357325',
    projectId: 'prakmobile-9c0f6',
    storageBucket: 'prakmobile-9c0f6.appspot.com',
    iosBundleId: 'com.example.valorantApp',
  );
}
